# Tomcat settings
server:
  port: ${TOMCAT_PLAT_PORT:7080}
  context-path: /
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
    basedir: ./

# smartKey setting
icd:
  server-address: 127.0.0.1:7777
  generate-number: 100

